# Generated by Django 3.2.16 on 2023-04-13 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_navermoviedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentiword_dict1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=32)),
                ('label', models.IntegerField()),
            ],
        ),
    ]
