# Generated by Django 3.2.16 on 2023-04-13 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_user_kakao_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_kakao_data',
            old_name='t_date',
            new_name='time',
        ),
    ]
