# Generated by Django 3.2.16 on 2023-04-25 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_t_date_user_kakao_data_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='TrainingData',
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
