# Generated by Django 3.2.16 on 2023-04-13 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_sentiword_dict1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentiword_dict2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=10)),
                ('sentiment', models.CharField(max_length=10)),
                ('frequency', models.FloatField()),
                ('degree1', models.FloatField()),
                ('degree2', models.FloatField()),
            ],
        ),
    ]
