# Generated by Django 3.2.16 on 2023-04-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_sentiword_dict2'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_kakao_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=10)),
                ('content', models.CharField(max_length=200)),
                ('t_date', models.TimeField()),
            ],
        ),
    ]
